name: hr_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

# For API 
  http: 0.12.0+4
  flutter_html: 0.11.1
  json_annotation: 3.0.1
  json_serializable: 3.2.5
  intl: ^0.16.1
  shared_preferences: ^0.5.6+2
  provider: 4.0.4
  chopper: 3.0.2
  dio: 3.0.9

  image_picker:
  rflutter_alert: ^1.0.2
  flutter_spinkit: ^3.1.0
  progress_dialog: ^1.2.1
  toast: ^0.1.5
  
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/ic_roketin.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets :
  - assets/roketin.png

  - assets/images/home.png
  - assets/images/history.png
  - assets/images/profile.png

  - assets/images/home_active.png
  - assets/images/history_active.png
  - assets/images/profile_active.png

  - assets/images/ic_calendar.png
  - assets/images/ic_check.png
  - assets/images/ic_clock.png
  - assets/images/ic_remote.png
  - assets/images/ic_sick.png

  - assets/images/avatar.png
  - assets/images/dot.png
  - assets/images/login.png
  - assets/images/logout.png
  - assets/images/account.png

  - assets/images/upload.png
  - assets/images/cancel.png
  #18-6-96


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts :
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
